---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-config
  namespace: postgresql
type: Opaque
data:
  password: YWRtaW5wYXNzd29yZDEyMwo=
