---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-server
  labels:
    app: postgres-server
  namespace: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-server
