---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-server
  namespace: postgresql
  
spec:
  selector:
    matchLabels:
      app: postgres-server
  template:
    metadata:
      labels:
        app: postgres-server
        namespace: postgresql
    spec:
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - name: postgres-server
          image: postgres:latest
          volumeMounts:
          - name: postgres-pv-storage
            mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - name: postgres-server
            containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret-config
                key: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata


